### ISSUE TITLE
Several Questions

### ISSUE THREAD

**Issue by YuukiHenri** [storyboardcreativity/zraw-parser#1]
Can you provide us some information about what happened to ZRAW in version 0.9.4? I checked your github project but didn't find the exact answer. I now know that with a software which is later than 0.9.4 the camera provides a ZRAW file containing a 10bit 420 HEVC video stream, does this mean that ZRAW no longer has any RAW features after 0.9.4, but is just a HEVC video? Or does ZRAW indeed become a Partial Debayered RAW? And, most importantly, what kind of color gamut and gamma does the HEVC video obtained with the tools you provide have after version 0.9.4 and how should I grade it? Thanks a lot and great credit to your work!

**Comment by storyboardcreativity** [comment]
I'll make a video about it soon.

Yes, 0.94 and next versions provide ZRAW files with HEVC data only (but with a huge bitrate). Z CAM lied to all users and made changes to ZRAW without any notification to camera users. There is no any RAW data in these files. It's just a HEVC video.

About color gamut... I did not check yet. But it seems like Z-Log2. You can try it by yourself or soon I'll make check using X-Rite ColorChecker Video and publish a result.

About RAW recording: you can rollback your firmware to 0.93 using my special firmware. What camera do you have?

**Comment by YuukiHenri** [comment]
I currently have an E2 S6, but unfortunately I conducted a firmware upgrade, so for now I only have the HEVC encoded Z"RAW" :(

**Comment by storyboardcreativity** [comment]
> I currently have an E2 S6, but unfortunately I conducted a firmware upgrade, so for now I only have the HEVC encoded Z"RAW" :(

If smb gives me E2-S6 for tests, I'll make a rollback firmware version (0.98 to 0.93)
