### ISSUE TITLE
No Audio Output

### ISSUE THREAD

**Issue by Huffman956** [storyboardcreativity/zraw-parser#3]
**Bug**
/ AAC Audio stream not transferred to output file

**Info**
/ ZRAW parser / 0.4.3-alpha & 0.4.5-alpha
/ Zcam E2-M4 & E2C / v0.98
/ Windows 10 / Version 10.0.19043 Build 19043

**Comment by storyboardcreativity** [comment]
Fixed in this commit:
6b91200e36640a0bd2735977ac014e6a733ca93f

(now audio tracks are saved in separate ".mov" file in the output folder)
