### ISSUE TITLE
Add *.mov mask in opendialog

### ISSUE THREAD

**Issue by s3merer** [storyboardcreativity/zraw-parser#4]

**Comment by storyboardcreativity** [comment]
Fixed in this commit:
cbd6f82d8b42dc80ed586d599d8480c1d56e0bff

Permalink to this fix:
https://github.com/storyboardcreativity/zraw-parser/blob/cbd6f82d8b42dc80ed586d599d8480c1d56e0bff/src/BatchConversionListUserControl.hpp#L183
